version: "3"
services: 
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:

      - DB_PASSWORD=123Password
      - DB_USER=postgres
      - DB_NAME=CsitProject
      - DB_HOST=postgres
      - DB_PORT=5432
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123Password
      - POSTGRES_DB=CsitProject
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: